######################################################################
# Automatically generated by qmake (1.07a) Mon Dec 31 10:48:00 2007
######################################################################

TEMPLATE = app
CONFIG -= moc qt
#CONFIG += console
DESTDIR=../..
INCLUDEPATH += .

# Input
SOURCES += FileWatcher.cpp
