"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    data_files=['MarkCommercials.cfg'],
    app=['MarkCommercials.py'],
    options=dict(py2app=dict(
        plist=dict(
            LSBackgroundOnly=True,
        ),
    )),
)
